auto_route_generator/lib/src/route_paramter_config.dart, auto_route_generator/lib/utils.dart
**Fixes #74**
``element.source.isInSystemLibrary``  is returing ``true`` for any source that have ``dart:*`` on the uri.
```dart
//from 'package:analyzer/src/generated/source.dart'
abstract class BasicSource extends Source {
...
@override
bool get isInSystemLibrary => uri.scheme == 'dart';
...
}
```
And as I can see here from the [Dart Docs](https://api.dart.dev/stable/2.7.2/index.html) we need to import any system library to use it except ``dart:core``
> Except for dart:core, you must import a library before you can use it.
=> only ignore dart:core when importing

README.md, auto_route/README.md, auto_route/lib/auto_route_annotations.dart, auto_route/lib/src/router_base.dart, auto_route_generator/lib/router_class_generator.dart, auto_route_generator/lib/src/route_paramter_config.dart, auto_route_generator/lib/src/router_config.dart
#88 
#90 
This is my $Router class : 
```dart
@MaterialAutoRouter(routesClassName: 'BusRoute', generateRouteList: true , routePrefix: '/bus/')
class $MyBusRouter{
BusFilterScreen busFilterScreen ;
BaseLoadingScreen baseLoadingScreen ; 
}
```
```dart
abstract class BusRoute {
static const busFilterScreen = '/bus/bus-filter-screen';
static const baseLoadingScreen = '/bus/base-loading-screen';
static const all = [
busFilterScreen,
baseLoadingScreen,
];
}
class MyBusRouter extends RouterBase {
@override
List<String> get allRoutes => const [
BusRoute.busFilterScreen,
BusRoute.baseLoadingScreen,
];
//This will probably be removed in future versions
//you should call ExtendedNavigator.ofRouter<Router>() directly
static ExtendedNavigatorState get navigator => …
```
=> Adds routePrefix option and allRoutes getter function code for router class

auto_route/lib/src/extended_navigator.dart
Since the last flutter update, navigation on the web was working without the route being updated on the browser url.
This quick change makes it work in my case, but I don't have the knowledge to know if it will work for everybody else, I notice the problem also occurs with flutter native navigator when using onGenerateRoute, so it's probably not even an error with your plugin.
Also, the plugin is great, keep it up 👍
=> ref(navigator): Report route update

auto_route/lib/src/router/widgets/auto_router.dart
Since all of the Flutter_UXR examples name their widgets with "Screen" instead of "Page", it will make the snippets much more concise if there is an `EmptyRouterScreen`
=> Add EmptyRouterScreen

auto_route_generator/lib/src/models/route_parameter_config.dart
@Milad-Akarie 
The args class is being generated with optNum function when the value is bool
=> fix(generator): Bool opt type as num

README.md
Greetings,
Recently tried the guide to implement this amazing library and got confused in the 'Finalize the setup' section, thought AutoRouterDelegeate was a class I had to implement, but figured out that it was a class from the library.
Details: 
- changed AutoRouterDelegeate to AutoRouterDelegate
- changed parameter named _appDelegate to _appRouter
- add space before brackets
=> docs: code syntax error on 'Finalize the setup' section for README.md

auto_route/lib/src/router/controller/routing_controller.dart
Since the list is `const` it is implicitly immutable due to being a compile time constant.  Removed the const which fixed the issue  described here https://github.com/Milad-Akarie/auto_route_library/issues/822
=> Fixed issue causing pendingChildren to become immutable

auto_route/lib/src/router/widgets/auto_tabs_router.dart
You can read about it here: https://stackoverflow.com/questions/58802223/flutter-ticker-must-be-disposed-before-calling-super-dispose
Stumbled upon it in a project of mine, when page that used AutoTabsScaffold got a build depending on some provider that have changed;
=> Animation controller should be disposed

auto_route_generator/lib/src/code_builder/library_builder.dart
just adding more information to the duplication route exception
before
```
Duplicate route names must have the same path! [null]
Note: Unless specified, route name is generated from page name.
```
after
```
Duplicate route names must have the same path! (name: null, path: /some/path)
Note: Unless specified, route name is generated from page name.
```
=> extended message for duplicate route name

auto_route/lib/src/router/widgets/auto_router.dart
Thanks for the amazing package!!
Was getting a flash white screen for a split second, this is solved with a `placeholder` in the `routerDelegate`, but the sub-routes don't have a delegate. So I have added a placeholder to the `AutoRouter` widget, I have tested it and it works as intended. 
Might be related to: https://github.com/Milad-Akarie/auto_route_library/issues/619
=> added placeholder to nested autoRouter

auto_route/lib/src/router/auto_route_page.dart
When using `AdaptiveRoute` on Android everything works as expected but on iOS custom `PageTransitionsTheme` is ignored. 
```
PageTransitionsTheme(
builders: {
TargetPlatform.android: CustomAndroidTransitionsBuilder(), // not ignored on Android device 
TargetPlatform.iOS: CustomiOSTransitionsBuilder(), // ignored on iOS device
},
)
```
The reason is that `_PageBasedCupertinoPageRoute` never uses `PageTransitionsTheme`:
```
... _PageBasedCupertinoPageRoute
@override
Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
return buildPageTransitions<T>(this, context, animation, secondaryAnimation, child);
}
... PageBasedMaterialPageRoute
@override
Widget buildTransitions(BuildContext context, Animation<double> …
```
=> fix PageTransitionsTheme ignored on iOS

auto_route/lib/src/router/widgets/auto_tabs_router.dart
Not disposed AnimationController leaks potentially a Ticker, more about it here: https://stackoverflow.com/questions/58802223/flutter-ticker-must-be-disposed-before-calling-super-dispose
PR fixes the following problem:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
AutoTabsRouterState#6d120(ticker active) was disposed with an active Ticker.
AutoTabsRouterState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the …
```
=> Animation controller from AutoTabsRouter should be disposed

auto_route/pubspec.yaml
This auto_route version won't work on the SDK lower from 2.17.x because of
```
../../.pub-cache/hosted/pub.dartlang.org/auto_route-4.0.1/lib/src/router/provider/auto_route_information_provider.dart:20:47: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../fvm/versions/2.10.5/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
location: WidgetsBinding.instance.window.defaultRouteName);
```
=> Adds compatibility lock

auto_route/lib/src/router/widgets/auto_tabs_router.dart
This is a continuation from https://github.com/Milad-Akarie/auto_route_library/pull/1093.
The order of invocations inside dispose() method is critical because `super.dispose()` validates that all AnimationControllers have been disposed. Therefore we first must dispose the animation controller, then call `super.dispose()`.
The official documentation suggests to call `super.dispose()` as the last invocation when overriding the `dispose()` method.
_Implementations of this method should end with a call to the inherited method, as in super.dispose()._ [Source](https://api.flutter.dev/flutter/widgets/State/dispose.html)
=> Fix animation controller dispose

auto_route_generator/lib/auto_route_generator.dart, auto_route_generator/pubspec.yaml
[Setup And Usage](https://pub.dev/packages/auto_route#setup-and-usage) section of the documentation contains two examples. While the example with `$AppRouter`:
```dart
@MaterialAutoRouter(              
replaceInRouteName: 'Page,Route',              
routes: <AutoRoute>[              
AutoRoute(page: BookListPage, initial: true),              
AutoRoute(page: BookDetailsPage),              
],              
)              
class $AppRouter {}              
```
works, another example which using `part` file:
```dart
part 'app_router.gr.dart';      
@MaterialAutoRouter(              
replaceInRouteName: 'Page,Route',              
routes: <AutoRoute>[              
AutoRoute(page: BookListPage, initial: true),              
AutoRoute(page: BookDetailsPage),              
],              
) …
```
=> Fix "Router class name must be prefixed with $" error when using part builder

auto_route/lib/src/common/auto_route_annotations.dart, auto_route/lib/src/router/auto_route_page.dart, auto_route_generator/lib/src/code_builder/root_router_builder.dart, auto_route_generator/lib/src/resolvers/route_config_resolver.dart
This pull request adds availability to pass `opaque` property into `_NoAnimationPageRouteBuilder` when `AdaptiveRoute` is used for `kIsWeb`. Quite similar like `cupertinoPageTitle` which would only be used for iOS.
What do you think, should I rename `customRouteOpaque` to more generic like `routeOpaque`?
=> add opaque property to AdaptiveRoute

auto_route/lib/src/router/auto_route_page.dart
Thanks to that users will have the ability to access child widget from AutoRoutePage.
Fixes: https://github.com/Milad-Akarie/auto_route_library/issues/1137
=> feat: Add a getter to expose child widget from AutoRoutePage

auto_route/lib/src/router/widgets/auto_tabs_scaffold.dart
Add FAB builder to `AutoTabsScaffold`.
The `floatingActionButton` parameter is retained. If it is specified the `floatingActionButtonBuilder` parameter is ignored. Please, let me know if you think this should be changed.
Closes #1180
Also related: #545
=> Add FAB builder to `AutoTabsScaffold`

auto_route/lib/src/router/widgets/auto_page_view.dart, auto_route/lib/src/router/widgets/auto_tab_view.dart, auto_route/lib/src/router/widgets/auto_tabs_router.dart
Changes that are similar to https://github.com/Milad-Akarie/auto_route_library/pull/1321 due to inactivity of that PR.
=> fix: fixed animation duration and jumpTo when animatePageTransition is false

README.md
I search link to the AutoRoute-helper plugin in documentation for a long time.
I think that it will be more convenient for developers who want to make migration faster.
=> Make link for AutoRoute-helper in docs

README.md
This fixes the indentation of build configuration examples in the README document
=> Fix indentation on build configuration examples

auto_route/lib/src/router/controller/auto_route_guard.dart
I was updating my project to use the latest auto_route and saw the new `redirect` functionality added since `7.2.3`, it seemed to work great except when you specifically want the redirected page to `replace` the current one. I saw the `replace` argument didn't change anything and by looking at the source code I saw it wasn't properly delegated.
Note: I did the same thing for the `onFailure` argument.
=> fix: delegate missing arguments in auto_route_guard redirect

README.md
Minor update to docs for missing bracket on if statement in deeplink example code. Also added some spacing too.
=> Updated README.md with missing bracket on deeplink example

auto_route/lib/src/router/controller/routing_controller.dart, auto_route/lib/src/router/transitions/custom_page_route.dart
Introduced new `opaque` argument in `AutoPageRouteBuilder`.
Allows the `opaque` argument to be used when calling `pushWidget()`.
=> feat(auto_route): add `AutoPageRouteBuilder.opaque` argument

README.md
When in the pub.dev page, the link of pre-v6 documentation is invalid (Github shows the 404 page).
I fixed the issue by changing the link to the direct URL of the file in Github.
=> fix: invalid pre v6 documetation link

auto_route/lib/src/route/auto_route_config.dart
This MR is very trivial but add some nice information about issue with the route.
**Before change**
flutter: Root-paths must start with a "/" or be a wild-card
**AfterChange**
flutter: Root-paths must start with a "/" or be a wild-card: app_update
Hope that will help some of you.
=> Add path related to error

auto_route/lib/src/router/widgets/auto_tab_view.dart
Hi, 
The `AutoTabsRouter.tabBar` widget is not updating correctly when a new list of routes is passed to it.
| Before  | After |
| ------------- | ------------- |
| <video src="https://github.com/Milad-Akarie/auto_route_library/assets/105102312/02a7ee79-a6ba-4c14-ad5b-b3eff3f09b2d">  | <video src="https://github.com/Milad-Akarie/auto_route_library/assets/105102312/5685ab4e-acf1-4627-bbc0-abcc8507a9ac">|
Here is an example code to reproduce the problem :
```dart
void main() {
runApp(MyApp());
}
class MyApp extends StatelessWidget {
MyApp({super.key});
final _appRouter = AppRouter();
@override
Widget build(BuildContext context) {
return MaterialApp.router(
debugShowCheckedModeBanner: false,
routerConfig: _appRouter.config(),
);
}
}
@RoutePage()
class HomeScreen extends StatefulWidget { …
```
=> fix: ensure dynamic tab updates are handled in AutoTabsRouter.tabBar

auto_route/lib/src/route/auto_route_config.dart
For AutoRoute: renamed _changePath to _change. Added copyWith() Refactored changePath() to use copyWith.
The use case is being able to delay the generation of the AutoRoute config. Currently I have a situation where some AutoRoute configs are defined and reorganised automatically. I needed to be able to override the children of the auto route but because of the slight variance of constructor param types to internal member var types, there wasn't a clean way to do it.
This should fill in the missing blanks
=> Added copyWith to AutoRoute

auto_route/lib/src/router/controller/routing_controller.dart, auto_route/lib/src/router/widgets/auto_tabs_router.dart, auto_route/test/nested_tabs_router/tabs_router_tests.dart, auto_route/test/test_page.dart
A fix for #1759. Also includes a general test for popping in the presence of a `homeIndex`.
=> fix: keep TabsRouter.homeIndex in sync with AutoTabsRouter.homeIndex

auto_route/lib/src/common/auto_route_observer.dart
Fixes #1734 
Dart 3 restricted the use of the `with` keyword for classes declared as `mixin class` or `mixin`. This PR changes AutoRouteAware from `abstract class AutoRouteAware` to `abstract mixin class AutoRouteAware`.
=> feat: add back mixin to AutoRouteAware

README.md
This replaces the deprecated `flutter pub run` with the new `dart run` command in the readme
=> Replace deprecated flutter pub run with dart run in readme

auto_route/pubspec.yaml
The latest release of `auto_route` includes the `PopScope` widget, which was introduced in  Fluter version `3.14.0-7.0.pre`, and in stable `3.16.0`. I just updated the minimum Flutter SDK constraint to indicate that.
The latest release of auto_route (`7.8.5`) will fail to install for users who are not on the latest stable version. You may want to consider [retracting](https://dart.dev/tools/pub/publishing#retract) that release and publishing a new version with an updated SDK constraint.
=> fix: minimum flutter version constraint

README.md, auto_route/example/lib/mobile/main.dart, auto_route/lib/src/route/auto_route_config.dart, auto_route/lib/src/router/auto_route_page.dart, auto_route/lib/src/router/widgets/custom_cupertino_transitions_builder.dart
**Issue**: `CupertinoNavigationBar` and `CupertinoSliverNavigationBar` can not get current route title and previous route title.
**Сonsequences**: 
- In case of title: if a title was not provided to `CupertinoNavigationBar`/`CupertinoSliverNavigationBar` then [an `AssertionError` will be thrown: "largeTitle was not provided and there was no title from the route." in debug mode. In release - throws a runtime error](https://github.com/flutter/flutter/blob/defa2b7443651446e7724ab1903d15518d707877/packages/flutter/lib/src/cupertino/nav_bar.dart#L1372C5-L1380C7).
- in case of previous screen title: the back label of `CupertinoNavigationBarBackButton` will be empty(if a string was not passed explicitly to `previousPageTitle`)
<details>
<summary>Code to reproduce:</summary>
```dart
import …
```
=> fix: unable to get the label for back button(previous route title) and current route title on CupertinoNavigationBar and CupertinoSliverNavigationBar

auto_route/lib/src/router/widgets/auto_tabs_router.dart
The ticker was not disposed because the TabController was not disposed this leads to errors, which we encountered in one of our integration tests.
=> Dispose ticker

README.md
Fixed wrongfully formatted code in the readme after commit 45e643a74b13746e77bb12b8cc14f19fe03b95f3.
This also closes #1899
=> fix readme.md formatting

auto_route/lib/src/router/controller/navigation_history/navigation_history_base.dart, auto_route/lib/src/router/controller/navigation_history/web_navigation_history.dart, auto_route/pubspec.yaml
Migrate from dart:html to package:web to support wasm
[Migrate to package:web](https://dart.dev/interop/js-interop/package-web#conditional-imports)
=> Migrate to package:web

auto_route/lib/src/route/auto_route_config.dart, auto_route/test/matcher_test.dart
Resolves issue #2035  where only the last redirect in a collection is persisted. I overrode `RedirectRoute`'s `name` property appended the `path` and `redirectTo` to the `page.name` to make redirect routes unique from one another. I also added a handful of unit tests verifying the fix, and verified that the rest of the test suite passes. Please let me know if there is an alternative fix you would prefer to this issue. Thank you again.
=> Give RedirectRoutes a unique name to allow multiple in a collection

auto_route_generator/lib/src/models/route_parameter_config.dart
This PR allows the generator add the `required` to named parameters in function parameters' arguments. 
In the example screen below, the `onPressed` parameter is a function and `name` is a required named parameter. 
```dart
@RoutePage()
class MainPage extends StatelessWidget {
const MainPage({
required this.onPressed,
});
final void Function({required String name}) onPressed;
@override
Widget build(BuildContext context) {
return const Scaffold(
body: Center(
child: Text('Hello World!'),
),
);
}
}
```
In the current version of auto_route, the generated code omits the `required` keyword by outputting: 
```dart
required void Function({String name}) onPressed,
```
This PR fixes it by outputting: 
```dart
required void Function({required String name}) onPressed,
```
See …
=> Add required keyword to named required parameters in function parameters' arguments

auto_route/lib/src/common/parameters.dart
generator will  generate 
```
queryParams.getList(
'relationships',
const [],
)
```
but getList dosent support default value.
full code:
```dart
@RoutePage()
class AddPalSlipRelationshipPage extends LinjiePage {
final List<String> relationships;
const AddPalSlipRelationshipPage(
{super.key, @QueryParam("relationships") this.relationships = const [],});
@override
ConsumerState<ConsumerStatefulWidget> createState() {
return _SelectRelationshipPage();
}
}
```
```dart
static PageInfo page = PageInfo(
name,
builder: (data) {
final queryParams = data.queryParams;
final args = data.argsAs<AddPalSlipRelationshipRouteArgs>(
orElse: () => AddPalSlipRelationshipRouteArgs(
relationships: queryParams.getList(
'relationships',
const [],
)));
return AddPalSlipRelationshipPage(
key: args.key, …
```
=> Parameters getList support defaultValue

README.md, auto_route/lib/src/route/auto_route_config.dart, auto_route/lib/src/route/route_type.dart, auto_route/lib/src/router/auto_route_page.dart
Update the `durationInMilliseconds` and `reverseDurationInMilliseconds` parameters in the CustomRoute to use the native [Duration](https://api.dart.dev/dart-core/Duration-class.html) type.
The Duration type is the standard type for representing durations in Dart, so there is no need to use an Int type to represent route durations.
=> refactor(custom_route): update route duration type from int to Duration

auto_route/CHANGELOG.md, auto_route/lib/src/router/controller/auto_router_delegate.dart, auto_route/lib/src/router/widgets/auto_route_navigator.dart, auto_route/lib/src/router/widgets/auto_router.dart, auto_route/lib/src/router/widgets/auto_tabs_router.dart, auto_route/pubspec.yaml
This PR introduces 2 changes.
1. Feat: Expose ` routeTraversalEdgeBehavior` from the underlying `Navigator`
2. Fix: When using the default `AutoTabRouter` (`IndexedStack` under the hood) the semantic and focus tree of invisible tabs was not excluded which effects focus traversal as it allows the focus to move to hidden tabs.
=> fix-focus-managment

auto_route/lib/src/route/route_data.dart
This PR try to fix : https://github.com/Milad-Akarie/auto_route_library/issues/2206
It well fix the issue but i didn't know what can be the regression.
Hi @Milad-Akarie, what is the reason to not complete the popCompleter when _isReevaluating is true ?
=> Fix: Allow PopCompleter to complete during route reevaluation
