Milad-Akarie/auto_route_library

- README.md
Changed ExtenedNavigator to ExtendedNavigator in the navigation section
> updated Readme file, Fixed a typo

- auto_route_generator/lib/src/route_paramter_config.dart
- auto_route_generator/lib/src/router_config_resolver.dart
#97 
[x] Support generics or type parameterised functions
[x] Support named , optional , and positional parameters for function types
[x] Support importing return types for function types
[x] Support nested FunctionType ( `void Function(Function(int) , double)` ) parameters
[x] Support Future<FunctionType>
[x] Support type parameters that extend that some super class type . So import should happen for this super class :  ( `void Function<T extends TypeA>( int a, Type B)` )
+ TypeA Function(TypeB , TypeA , { TypeC typec , TypeD typed });
+ TypeA Function<T,List\<R>,S>(TypeB , TypeA , [ TypeC typec , TypeD typed ] );
+ final void Function<G extends TypeA>(LocationItem , CheckListItem , G subTypeOfTypeA ,{Future<CoreConfig> a , CreateOrderRequest b} ) onChanged;
**Function types inside …
> Support for Complex function types for importing sources of the types

- README.md
- auto_route/README.md
- auto_route/example/README.md
- auto_route/lib/auto_route_annotations.dart
- auto_route/lib/src/extended_navigator.dart
- auto_route/lib/src/route_data.dart
- auto_route/lib/src/route_def.dart
- auto_route/lib/src/route_matcher.dart
- auto_route/lib/src/router_base.dart
- auto_route/lib/src/router_utils.dart
- auto_route/lib/src/transitions_builders.dart
- auto_route/pubspec.lock
- auto_route/pubspec.yaml
- auto_route_generator/lib/import_resolver.dart
- auto_route_generator/lib/router_class_generator.dart
- auto_route_generator/lib/src/route_config.dart
- auto_route_generator/lib/src/route_config_resolver.dart
- auto_route_generator/lib/src/route_parameter_config.dart
- auto_route_generator/lib/src/router_config_resolver.dart
- auto_route_generator/lib/utils.dart
- auto_route_generator/pubspec.yaml
> Fix README file links

- auto_route/CHANGELOG.md
- auto_route/lib/auto_route.dart
- auto_route/lib/src/extended_navigator.dart
- auto_route/lib/src/router_base.dart
- auto_route/pubspec.yaml
- auto_route_generator/CHANGELOG.md
- auto_route_generator/lib/router_class_generator.dart
- auto_route_generator/pubspec.yaml
- example/lib/main.dart
- example/lib/router/router.dart
- example/lib/screens/home_screen.dart
- example/lib/screens/users/sub/sub/posts_details.dart
- example/pubspec.lock
Clean up auto_route index file
> Downgrade path package to >= 1.6.4 to solve conflict with flutter_test

- README.md
- auto_route/CHANGELOG.md
- auto_route/README.md
- auto_route/lib/src/route/page_route_info.dart
- auto_route/lib/src/router/auto_route_page.dart
- auto_route/lib/src/router/controller/routing_controller.dart
- auto_route/lib/src/router/parser/route_information_parser.dart
- auto_route/lib/src/router/widgets/auto_router.dart
- auto_route/lib/src/router/widgets/auto_tabs_router.dart
- auto_route/pubspec.yaml
- auto_route_generator/CHANGELOG.md
- auto_route_generator/pubspec.yaml
- example/lib/mobile/main.dart
- example/lib/mobile/router/router.dart
- example/lib/mobile/router/router.gr.dart
- example/lib/mobile/screens/books/routes.dart
- example/lib/mobile/screens/home_page.dart
- example/lib/mobile/screens/login_page.dart
> - Refactor some code

- auto_route/.gitignore
- auto_route/lib/auto_route.dart
> export navigation_failure.dart

- auto_route_generator/.gitignore
- auto_route_generator/CHANGELOG.md
- auto_route_generator/lib/src/code_builder/route_info_builder.dart
> PageRouteInfo<void>

- auto_route/README.md
Here is the typo I fix in this PR: AutoRouterDeleg_e_ate -> AutoRouterDelegate
> Fix a typo in README.md

- auto_route/CHANGELOG.md
- auto_route/example/lib/mobile/router/router.gr.dart
- auto_route/example/lib/mobile/screens/books/book_list_page.dart
- auto_route/example/lib/mobile/screens/home_page.dart
- auto_route/example/lib/web/router/web_router.dart
- auto_route/example/lib/web/router/web_router.gr.dart
- auto_route/example/lib/web/web_main.dart
- auto_route/lib/src/router/controller/auto_route_guard.dart
- auto_route/lib/src/router/controller/auto_router_delegate.dart
- auto_route/pubspec.yaml
- auto_route_generator/lib/src/code_builder/route_info_builder.dart
- auto_route_generator/lib/src/models/route_parameter_config.dart
- auto_route_generator/pubspec.yaml
- Fix conflict when param name is 'name' #824
> - Fix Bad state: No element exception when setting initialRoutes #826

- auto_route/CHANGELOG.md
- auto_route/example/lib/mobile/router/router.gr.dart
- auto_route/example/lib/mobile/screens/books/book_list_page.dart
- auto_route/example/lib/mobile/screens/home_page.dart
- auto_route/example/lib/web/router/web_router.dart
- auto_route/example/lib/web/router/web_router.gr.dart
- auto_route/lib/src/router/controller/auto_route_guard.dart
- auto_route/lib/src/router/controller/auto_router_delegate.dart
- auto_route/lib/src/router/controller/navigation_history.dart
- auto_route/lib/src/router/controller/routing_controller.dart
- auto_route/lib/src/router/widgets/auto_tabs_router.dart
- auto_route/pubspec.yaml
- Refactor navigation history and set kept history records to 20 entries max
> - Fix navigateNamedTo does not update the stack #831

- auto_route/lib/src/router/controller/auto_router_delegate.dart
- auto_route/lib/src/router/provider/auto_route_information_provider.dart
Added RouteInformationReportingType type with RouteInformationReportingType.navigate as default
> Fixed overriden routerReportsNewRouteInformation

- README.md
declarate instead of declerate
> typo error fix

- .idea/libraries/Dart_SDK.xml
- auto_route/CHANGELOG.md
- auto_route/README.md
- auto_route/example/android/gradle.properties
- auto_route/example/lib/mobile/main.dart
- auto_route/example/lib/mobile/router/router.dart
- auto_route/example/lib/mobile/router/router.gr.dart
- auto_route/example/lib/mobile/screens/books/book_list_page.dart
- auto_route/example/lib/web/router/web_router.dart
- auto_route/example/lib/web/router/web_router.gr.dart
- auto_route/lib/src/common/auto_route_annotations.dart
- auto_route/lib/src/router/auto_route_page.dart
- auto_route/lib/src/router/controller/auto_route_guard.dart
- auto_route/lib/src/router/controller/auto_router_delegate.dart
- auto_route/lib/src/router/controller/navigation_history.dart
- auto_route/lib/src/router/controller/routing_controller.dart
- auto_route/lib/src/router/provider/auto_route_information_provider.dart
- auto_route/pubspec.yaml
- auto_route/test/nested_router/router.dart
- auto_route_generator/CHANGELOG.md
- auto_route_generator/pubspec.yaml
- Add @optionalTypeArgs to AutoRoute annotations
- Fix AdaptiveRoute issue with CustomRoute
- Change analyzer constrains to include version 3.0.0
- Add notify flag to removeWhere method inside of StackRouter
> - Merge some readme file typo-fixes

- auto_route/lib/src/router/controller/routing_controller.dart
> Add currentPath semantics to routing controller

- auto_route/lib/src/router/parser/route_information_parser.dart
@Milad-Akarie 
This PR is related to this issue:
https://github.com/Milad-Akarie/auto_route_library/issues/1119
Milad, please check these changes and let me know if anything else is needed.
Thanks
> fix: url state decode issue

- auto_route/lib/src/router/auto_route_page.dart
- auto_route/lib/src/router/controller/routing_controller.dart
- auto_route/lib/src/router/widgets/auto_route_navigator.dart
- auto_route/lib/src/router/widgets/auto_tabs_router.dart
- auto_route/pubspec.yaml
- auto_route/test/nested_tabs_router/router.dart
- auto_route_generator/CHANGELOG.md
- auto_route_generator/lib/src/code_builder/deferred_pages_allocator.dart
- auto_route_generator/lib/src/code_builder/library_builder.dart
- auto_route_generator/lib/src/code_builder/root_router_builder.dart
- auto_route_generator/lib/src/models/route_config.dart
- auto_route_generator/lib/src/resolvers/route_config_resolver.dart
- auto_route_generator/lib/src/resolvers/router_config_resolver.dart
- auto_route_generator/pubspec.yaml
> allow analyzer 4.4.6

- auto_route_generator/lib/src/resolvers/route_config_resolver.dart
- auto_route_generator/lib/src/resolvers/type_resolver.dart
- auto_route_generator/pubspec.yaml
Fixes conflict with other packages that are on 5.0.0 already.
> Update to analyzer 5.0.0

- auto_route/lib/src/router/widgets/auto_page_view.dart
- auto_route/lib/src/router/widgets/auto_tab_view.dart
- auto_route/lib/src/router/widgets/auto_tabs_router.dart
I added as an optional parameter Axis scrollDirection in AutoTabsRouter.pageView() and AutoTabsRouter.tabBar()
> Add scrollDirection parameter

- README.md
Added missing TabsRouter controller to all exampels
> Update README.md Tab Navigation misleading examples

- auto_route/lib/src/router/controller/routing_controller.dart
- auto_route_generator/pubspec.yaml
There was a missing null-check on RoutingController.
https://github.com/djangoflow/auto_route_library/commit/d25d1baf16cd2f413b25dafedda1c6c24ca28ed7
> Fix "Null check operator used on a null value"

- README.md
Fix typo in the `README.md` file
> fix(typo): change `LoginRoute.apge` to `LoginRoute.page`

- README.md
changed code for popUntil in README.md from route.name to route.settings.name.
> changed code for popUntil in README.md

- README.md
- auto_route/example/ios/Runner.xcodeproj/project.pbxproj
- auto_route/example/lib/mobile/main.dart
- auto_route/example/lib/mobile/router/router.dart
- auto_route/example/lib/web_demo/router/web_auth_guard.dart
- auto_route/example/lib/web_demo/router/web_router.dart
- auto_route/example/lib/web_demo/router/web_router.gr.dart
- auto_route/example/lib/web_demo/router/web_verify_page.dart
- auto_route/example/lib/web_demo/web_main.dart
- auto_route/lib/src/route/auto_route_config.dart
- auto_route/lib/src/route/route_data.dart
- auto_route/lib/src/router/auto_route_page.dart
- auto_route/lib/src/router/controller/auto_route_guard.dart
- auto_route/lib/src/router/controller/auto_router_delegate.dart
- auto_route/lib/src/router/controller/root_stack_router.dart
- auto_route/lib/src/router/controller/routing_controller.dart
docs: Add reevaluate listenable docs to README.md
feat: Add NavigationResolver.redirect method to auto-remove routes pushed by guards when resolving is complete
feat: Add AutoRoute.guarded constructor for cleaner single guard implementation
> feat: Add global guards reevaluate listenable

- README.md
- old/pre_v6_README.md
Hi, I want to add back documentation for the pre-v6 versions. 
This may be helpful for anyone who is maintaining projects using these versions and is not ready to migrate to v6+ ones.
Thanks for your time.
> chore: add pre v6 documentation

- auto_route_generator/lib/src/builders/auto_router_builder_base.dart
- auto_route_generator/lib/src/builders/cache_aware_builder.dart
> Fix AutoRouteConfig.module() doesn't generate part of file correctly.

- auto_route_generator/pubspec.yaml
Updated analyzer version to be compatible with other packages
> Updated Analyzer package in "auto_route_generator"

- README.md
hey @Milad-Akarie,
I was going through the docs of auto_route package. I found some issues in the docs, which might confuse the users a bit about the overall sentence meaning and thereby not clearly conveying the explanation that you have written.
As I faced the same issue, I would like to take the opportunity to improve it and contribute for the same. I have raised the pull request. 
Are these changes valid? Do let me know in case of any improvements
> fix(docs): improve docs and fix typos

- README.md
As the title said, just a minor fix in order to update the correct path for the Nested Route image
> Fixed src image for Nested routes

- README.md
I believe my previous PR #1866 got overwritten by something, so here I propose it again.
> Fix `Readme.md` formatting, spelling and table of contents

- auto_route/lib/src/router/controller/routing_controller.dart
> Spelling mistake fix

- auto_route/lib/src/router/auto_route_page.dart
- auto_route/lib/src/router/controller/routing_controller.dart
Fix: https://github.com/Milad-Akarie/auto_route_library/issues/1938
> Fixed back gesture when nested navigator only has one entry

- README.md
Added command in installation section to easily add auto_route to projects
> fix: readme.md installation comand
